# src/AppBundle/Resources/config/serializer/Entity.User.yml
AppBundle\Entity\User:
  exclusion_policy: none
  properties:
    id:
      groups: ['user', 'auth-token']
    firstname:
      groups: ['user', 'auth-token']
    lastname:
      groups: ['user', 'auth-token']
    email:
      groups: ['user', 'auth-token']
    preferences:
      groups: ['user']
