# src/AppBundle/Resources/config/serializer/Entity.Place.yml
AppBundle\Entity\Place:
  exclusion_policy: none
  properties:
    id:
      groups: ['place', 'price']
    name:
      groups: ['place', 'price']
    address:
      groups: ['place', 'price']
    prices:
      groups: ['place']
    themes:
      groups: ['place']
